function [output] = interleaver(b)
%INTERLEAVER Using the provided b computes the new DSC array

% The interleaving intervals to be used.
%   These are generated by the PRNG 
%   x_(n+1) = mod(floor(3.1 * x_n + 13), 48) using 14 as seed
intervals = [8 37 31 13 5 28 3 22 33 19 23 36];

m = 48*b;

initBits = 1:m;

initDSC = zeros(48, b);

% Initialize the DSC 
for i = 0:(m-1)
    %initDSC(floor(i / b) + 1, mod(i, b) + 1) = floor(i/b) + 1;
    initDSC(floor(i / b) + 1, mod(i, b) + 1) = initBits(i+1);
end

newDSC = zeros(48, b);

dscUsed = zeros(1, m);

for s = 1:48
    for i = 1:b
        dsc = mod(s + intervals(i), 48) + 1;
        bit = find(newDSC(dsc, :) == 0, 1);
        dscUsed((s-1) * b + i) = dsc;
        newDSC(dsc, bit) = initDSC(s, i);
    end
end

output = newDSC;

end

